version: '3.8'

services:

  api:

    build: .

    ports:

      - "3000:3000"

    environment:

      - NODE_ENV=development

      - DB_HOST=postgres

      - DB_PORT=5432

      - DB_USERNAME=postgres

      - DB_PASSWORD=passwordcamilojpg

      - DB_DATABASE=articles_db

      - API_KEY=aquiTengo-Mysecret-Key

    depends_on:

      - postgres

    volumes:

      - .:/app

      - /app/node_modules

    command: pnpm run start:dev

  postgres:

    image: postgres:15-alpine

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: passwordcamilojpg

      POSTGRES_DB: articles_db

    ports:

      - "5433:5432"

    volumes:

      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data: